produto = float(input('Qual é o preço do produto? R$ '))
desconto = produto - (produto * 5 / 100)
acrescimo = produto + (produto * 10 / 100)
print('O produto que custava R$ {}, com desconto de 5% vai custar R$ {}.'.format(produto, desconto))
print('Caso o valor seja parcelado será R$ {}: '.format(acrescimo))
print('=' * 30)
print('Valores parcelados: ')
print('R$ {:.2f} X {:2} = R$ {:.2f}.'.format(produto, 1, produto / 1))
print('R$ {:.2f} X {:2} = R$ {:.2f}.'.format(acrescimo, 2, acrescimo / 2))
print('R$ {:.2f} X {:2} = R$ {:.2f}.'.format(acrescimo, 3, acrescimo / 3))
print('R$ {:.2f} X {:2} = R$ {:.2f}.'.format(acrescimo, 4, acrescimo / 4))
print('R$ {:.2f} X {:2} = R$ {:.2f}.'.format(acrescimo, 5, acrescimo / 5))
print('R$ {:.2f} X {:2} = R$ {:.2f}.'.format(acrescimo, 6, acrescimo / 6))
print('R$ {:.2f} X {:2} = R$ {:.2f}.'.format(acrescimo, 7, acrescimo / 7))
print('R$ {:.2f} X {:2} = R$ {:.2f}.'.format(acrescimo, 8, acrescimo / 8))
print('R$ {:.2f} X {:2} = R$ {:.2f}.'.format(acrescimo, 9, acrescimo / 9))
print('R$ {:.2f} X {:2} = R$ {:.2f}.'.format(acrescimo, 10, acrescimo / 10))
print('=' * 30)